services:

  app:
    build:
      context: app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    ports:
      - 3000:3000
    networks:
      - node-network
    depends_on:
      - db

  db:
    build:
      context: db
    command: --innodb-use-native-aio=0
    container_name: dbmysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - 8080:80
    depends_on:
      - db
      - app

networks:
  node-network:
    driver: bridge